name: Create and analyze project in CAST AIP

on:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
#     - name: Download CAST AIP Console Tools CLI
#       run: |
#         curl -L -o aip-console-tools-cli.jar https://github.com/CAST-Extend/com.castsoftware.aip.console.tools/releases/download/v2.5.5/aip-console-tools-cli.jar
#         chmod +x aip-console-tools-cli.jar
        
#     - name: Create Project
#       run: |
#         ping 10.77.225.194

    - name: security-devops-action
      uses: microsoft/security-devops-action@v1.6.0
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        path: /home/runner/work/mean-stack/mean-stack/.gdn/msdo.sarif
